#ifndef MK1MF_BUILD
    /* auto-generated by util/mkbuildinf.pl for crypto/cversion.c */
    #define CFLAGS cflags
    /*
     * Generate CFLAGS as an array of individual characters. This is a
     * workaround for the situation where CFLAGS gets too long for a C90 string
     * literal
     */
    static const char cflags[] = {
        'c','o','m','p','i','l','e','r',':',' ','g','c','c',' ','-','I','.',' ',
        '-','I','.','.',' ','-','I','.','.','/','i','n','c','l','u','d','e',' ',
        ' ','-','f','P','I','C',' ','-','D','O','P','E','N','S','S','L','_','P',
        'I','C',' ','-','D','Z','L','I','B','_','S','H','A','R','E','D',' ','-',
        'D','Z','L','I','B',' ','-','D','O','P','E','N','S','S','L','_','T','H',
        'R','E','A','D','S',' ','-','D','_','R','E','E','N','T','R','A','N','T',
        ' ','-','D','D','S','O','_','D','L','F','C','N',' ','-','D','H','A','V',
        'E','_','D','L','F','C','N','_','H',' ','-','m','a','r','c','h','=','a',
        'r','m','v','7','-','a',' ','-','W','a',',','-','-','n','o','e','x','e',
        'c','s','t','a','c','k',' ','-','D','T','E','R','M','I','O',' ','-','O',
        '3',' ','-','W','a','l','l',' ','-','D','O','P','E','N','S','S','L','_',
        'B','N','_','A','S','M','_','M','O','N','T',' ','-','D','O','P','E','N',
        'S','S','L','_','B','N','_','A','S','M','_','G','F','2','m',' ','-','D',
        'S','H','A','1','_','A','S','M',' ','-','D','S','H','A','2','5','6','_',
        'A','S','M',' ','-','D','S','H','A','5','1','2','_','A','S','M',' ','-',
        'D','A','E','S','_','A','S','M',' ','-','D','B','S','A','E','S','_','A',
        'S','M',' ','-','D','G','H','A','S','H','_','A','S','M','\0'
    };
    #define PLATFORM "platform: linux-armv4"
    #define DATE "built on: Sat Oct 20 19:41:30 2018"
#endif
